// Bundle the dashboard into one self-contained, gzipped file the ESP32 serves
// from flash. Produces three artifacts next to this script:
//
//   dashboard.html          — self-contained (qrp inlined, minified), for preview
//   dashboard.html.gz       — what actually ships to the device
//   src/dashboard_html_gz.h — PROGMEM byte array + length, #include it in main.cpp
//
// Run: node examples/esp32/build.js

import esbuild from "esbuild";
import fs from "node:fs";
import zlib from "node:zlib";
import path from "node:path";
import { fileURLToPath } from "node:url";
import process from "node:process";
import { Buffer } from "node:buffer";

const here = path.dirname(fileURLToPath(import.meta.url));
const rel = (p) => path.join(here, p);
const kb = (n) => (n / 1024).toFixed(2) + " KB";

// 1) bundle + minify the app (resolves the qrp core + forms imports, inlines them)
const built = await esbuild.build({
	entryPoints: [rel("app.js")],
	bundle: true,
	minify: true,
	format: "esm",
	target: "es2020",
	legalComments: "none",
	write: false
});
const appJs = built.outputFiles[0].text.trim();

// 2) inline it into the HTML shell -> one self-contained file
const template = fs.readFileSync(rel("dashboard.template.html"), "utf8");
const html = template.replace("/*__APP__*/", () => "\n" + appJs + "\n");
fs.writeFileSync(rel("dashboard.html"), html);

// 3) gzip it — the device serves this with Content-Encoding: gzip
const gz = zlib.gzipSync(Buffer.from(html), { level: 9 });
fs.writeFileSync(rel("dashboard.html.gz"), gz);

// 4) emit a PROGMEM header (no filesystem needed on the chip)
const rows = [];
for (let i = 0; i < gz.length; i += 16) {
	const slice = [...gz.subarray(i, i + 16)].map((b) => "0x" + b.toString(16).padStart(2, "0"));
	rows.push("  " + slice.join(", ") + ",");
}
const header = [
	"// Generated by build.js — do not edit. Regenerate: node build.js",
	"#pragma once",
	"#include <pgmspace.h>",
	"",
	"const unsigned char dashboard_html_gz[] PROGMEM = {",
	rows.join("\n"),
	"};",
	`const unsigned int dashboard_html_gz_len = ${gz.length};`,
	""
].join("\n");
fs.mkdirSync(rel("src"), { recursive: true });
fs.writeFileSync(rel("src/dashboard_html_gz.h"), header);

console.log("live dashboard (qrp core: state/el/when/list/derive), bundled + minified:");
console.log(`  app JS            ${kb(Buffer.byteLength(appJs))}`);
console.log(`  full HTML page    ${kb(Buffer.byteLength(html))}`);
console.log(`  gzipped (flash)   ${kb(gz.length)}   <- total device footprint`);
if (process.env.CI) process.exit(0);
